volumes:
  pg_data_production:
  static_production:
  media_production:

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dmitriyvzverev/kittygram_backend/
    env_file: .env
    volumes:
      - static_production:/static
      - media_production:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: dmitriyvzverev/kittygram_frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static_production:/static
  nginx:
    image: dmitriyvzverev/kittygram_nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_production:/static
      - media_production:/app/media
    depends_on:
      - backend
